# Generated by Django 3.2.16 on 2023-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_article',
            field=models.ImageField(blank=True, null=True, upload_to='image_category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='reference article'),
        ),
    ]
