# Generated by Django 3.2.16 on 2023-11-01 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0004_auto_20231101_1058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='reference Achat')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Montal total')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier Name')),
                ('supplier_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Number')),
                ('nui', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero Indentifiant Unique')),
                ('rc', models.CharField(blank=True, max_length=40, null=True, verbose_name='Registre du commerce')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero Telephone')),
                ('mail', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Adresse Email')),
                ('country', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.country')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.town')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
