# Generated by Django 3.2.16 on 2023-11-02 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20231101_1058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='reference transaction'),
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervenant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Intervenant Name')),
                ('intervenant_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Number')),
                ('matricule', models.CharField(blank=True, max_length=40, null=True, verbose_name='Matricule')),
                ('post_occuped', models.CharField(blank=True, max_length=150, null=True, verbose_name='Poste Occupé')),
                ('direction', models.CharField(blank=True, choices=[('Agency', 'Agency'), ('HQ', 'Head Quarter')], max_length=20, null=True, verbose_name='direction')),
                ('dept', models.CharField(blank=True, choices=[(1, 'account'), (2, 'Marketing'), (3, 'Administration'), (4, 'Technical')], max_length=20, null=True, verbose_name='department')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero Telephone')),
                ('mail', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Adresse Email')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.town')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='intervenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.intervenant'),
        ),
    ]
