# Generated by Django 3.2.16 on 2023-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20231102_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenant',
            name='dept',
            field=models.CharField(blank=True, choices=[('account', 'account'), ('Marketing', 'Marketing'), ('Administration', 'Administration'), ('Technical', 'Technical')], max_length=20, null=True, verbose_name='department'),
        ),
    ]
