# Generated by Django 3.2.16 on 2023-11-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_full_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='full_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Montal total'),
        ),
    ]
